# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: earth
day_night: false
font: 'native'
font_size: l

# SEO

site_type: Person
local_business_type: ''
org_name: ''
description: 'Pedro Perrusi personal page'
twitter: ''

# Contact (edit or remove options as required)

email: pedroperrusi@protonmail.com
address:
  city: Strasbourg
  region: Grand-Est
  postcode: '67000'
  country: France
  country_code: FR

# Site header

main_menu:
  enable: true
  align: l
  show_logo: false
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: true

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/pedroperrusi/pedroperrusi.github.io'
    content_dir: content
    branch: main
  avatar:
    gravatar: true
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
